### ISSUE TITLE
Update to wording for genre_spec.rb that causes student confusing

### ISSUE THREAD

**Issue by thebrianemory** [learn-co-curriculum/rails-cru-form_for-lab#12]
Submitted PR #11 to update wording to remove student confusion for why the test is failing.

The final test in `genre_spec.rb` uses the same wording as the previous test. The test for the new form and edit form have the same wording.

`it 'shows a new form that submits content and redirects and prints out params'`

This is a causing confusion for students as they think something is wrong with their new genre form when the issue is actually their edit genre form.

Updated the wording for the edit form test to instead read:

`it 'shows an edit form that submits content and redirects and prints out params'`

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
