### ISSUE TITLE
Update wording on Song spec to avoid confusion

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/rails-cru-form_for-lab#15]
This issue is similar to the existing one raised for the genre spec last year. The following capybara tests (within the Song spec) have identical descriptions, yet are testing two separate forms (new vs edit) in two separate view files:

```
 it 'shows a new form that submits content and redirects and prints out params' do
    visit new_song_path

    fill_in 'song[name]', with: "My song name"
    fill_in 'song[artist_id]', with: @artist.id
    fill_in 'song[genre_id]', with: @genre.id

    click_on "Create Song"

    expect(page).to have_content("My song name")
  end

  it 'shows a new form that submits content and redirects and prints out params' do
    @song = Song.create(name: "My Song", artist_id: @artist.id, genre_id: @genre.id)

    visit edit_song_path(@song)

    fill_in 'song[name]', with: "My edit"
    fill_in 'song[artist_id]', with: @artist.id
    fill_in 'song[genre_id]', with: @genre.id

    click_on "Update Song"

    expect(page).to have_content("My edit")
  end
```

Suggestion is to change the `it` block on the second test to indicate that the test is checking the Edit Song view/form.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. We updated the song_spec.rb to better differentiate the new song form and edit song from test.

Thanks! 💙
