### ISSUE TITLE
Song's Edit Form Test Typo

### ISSUE THREAD

**Issue by wendisha** [learn-co-curriculum/rails-cru-form_for-lab#17]
This typo persists (I see an issue was raised/closed about it before).
Two specs titles refer to the new form for Songs. 
Please change the second one to Edit, to avoid confusion.
Thanks in advance.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
