### ISSUE TITLE
tests needs revision 

### ISSUE THREAD

**Issue by ellevalentine** [learn-co-curriculum/rails-cru-form_for-lab#18]
spec for the songs form

 `shows a new form that submits content and redirects and prints out params`
  `shows a new form that submits content and redirects and prints out params`

should be 

 `shows a new form that submits content and redirects and prints out params`
  `shows an edit form that submits content and redirects and prints out params`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
