### ISSUE TITLE
Please revise this lab

### ISSUE THREAD

**Issue by endyranaudo** [learn-co-curriculum/rails-cru-form_for-lab#19]
Tests are looking for an integer for artist_id and genre_id, but you are given a text box. Please make this clear that it's supposed to be a number!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
