### ISSUE TITLE
Confusing typo in the spec! 

### ISSUE THREAD

**Issue by ioreka** [learn-co-curriculum/rails-cru-form_for-lab#20]
second song `form` test still says it's assessing the `new` but this should be `edit`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
