### ISSUE TITLE
Please update spec to be clear about which model is being assessed

### ISSUE THREAD

**Issue by ioreka** [learn-co-curriculum/rails-cru-form_for-lab#21]
multiple `navigate`, `form`, `index` test sections and difficult to see to which model they pertain - have to guess/infer

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
