### ISSUE TITLE
Testing specs do not allow for artist/genre selections

### ISSUE THREAD

**Issue by thegands** [learn-co-curriculum/rails-cru-form_for-lab#6]
The testing specs require the use of text fields (as far as i could tell) to associate a song with a song and artist on the song's show/edit pages. the user would have to know the ID of the genre and artist they would like to associate the song to in order for them to be able to create a song. this is not user friendly and also makes very little sense, which makes getting all the tests to pass a confusing mess.

the testing specs should allow for a dropdown or checkbox selection for artist/genre menus. this way it makes sense to both users and developers.

**Comment by AnnJohn** [comment]
thanks for raising this issue @thegands. We'll look at it soon!

**Comment by pletcher** [comment]
I'm pretty sure this is intentional, as later labs point to this exact issue as a pain point.
