### ISSUE TITLE
Post show page code from readme seemed to reference an object that didn't exist

### ISSUE THREAD

**Issue by erinpettigrew** [learn-co-curriculum/rails-cru-form_for-lab#8]
This very well could have been on my end, but I had issues with the below code on my post show page. The test data seemed to be a post without a category, so any attempts to call post.category caused a no method on nil class error.

Again, very well could have been an issue with how I went about the lab on my end though.

Thanks!

<%# app/views/posts/show.html.erb %>

<h2><%= @post.title %></h2>

Category: <%= link_to @post.category, category_path(@post.category) %>

<p><%= @post.description %></p>

**Comment by pletcher** [comment]
@erinpettigrew, thanks for opening this issue. I'm not sure that I can find that view in this lab -- should this issue point to another lab?
